### ISSUE TITLE
IN PC WE CANNOT SEE CERTAIN NAMES

### ISSUE THREAD

**Issue by PuneetGurjar** [efroemling/ballistica#112] opened 2020-07-15 09:27 UTC
in PC there is minor problem that if somebody has name in Hindi or any special font written then PC users can't see that name instead they see blank space, but that names are visible in android devices why

**Comment by Benefit-Zebra** [comment] 2020-07-15 09:35
This is because the language or font is not available on that platform.

**Comment by Benefit-Zebra** [comment] 2020-07-15 09:42
This is because the language or font which is used, is not available on that platform.

Language which aren't available on Windows/Linix:

- Chinese
- Arabic
- ChineseTraditional
- Korean
- Persian
- Hindi
- Vietnamese

**Comment by PuneetGurjar** [comment] 2020-07-15 09:58
but in new version Hindi is available
![Capture](https://user-images.githubusercontent.com/68325952/87531746-c8e13400-c6af-11ea-88f3-92a9cbc604a7.PNG)

**Comment by Benefit-Zebra** [comment] 2020-07-15 11:14
Windows/Linux are not supported for those languages. Therefore although the language script is present in game scripts, they cannot be displayed by the System on the screen.

**Comment by efroemling** [comment] 2020-07-16 20:59
As has been mentioned, the game simply can't draw those characters yet event if it has all the translations bundled with it. You'll see that the game has several 'fontSmall' textures which cover basic English and Cyrillic characters, but anything beyond that requires the game to ask the operating system to draw the characters, and I've not yet gotten that wired up for Linux or Windows. I do plan to though.

I'll go ahead and close this since it's a duplicate of #45.

**Closed by efroemling** 2020-07-16 20:59 UTC
