### ISSUE TITLE
Linux build mistaken as shared-library

### ISSUE THREAD

**Issue by Awesome-Logic** [efroemling/ballistica#139] opened 2020-07-30 07:01 UTC
The bombsquad executable won't open using file managers like nautilus. It has to be opened through terminal.
I think this can be fixed by using -no-pie in build file.

**Comment by Dliwk** [comment] 2020-07-30 08:17
Hmm, if you want to launch bombsquad as application (not just executable), you can create bombsquad.desktop file like this:
```desktop
[Desktop Entry]
Type=Application
Name=BombSquad
Comment=Blow up your friends in mini-games ranging from capture-the-flag to hockey!
Exec=bombsquad
Icon=bombsquad
Terminal=false
Categories=Game;
``` 
and put it in '/usr/share/applications' or '\~/.local/share/applications'.
If your icon-pack hasn't bombsquad icon, put [bombsquad.png](https://files.froemling.net/bombsquad/promo/BombSquadIcon.png) in '/usr/share/pixmaps'.
And at the end, create some launcher script in '/usr/bin' ('\~/.local/bin') like 
```bash
cd /opt/bombsquad
exec ./bombsquad
```

Now you can run bombsquad same as other applications :D
![изображение](https://user-images.githubusercontent.com/47295209/88898713-cce78700-d255-11ea-8297-cdd46e4b9c6d.png)

**Comment by Dliwk** [comment] 2020-07-30 08:30
A word about '-no-pie' ('-fno-pie'). This option simply tells compiler not to create a [position independent executable](https://en.wikipedia.org/wiki/Position-independent_code#PIE) and it can't help with opening using file managers.

**Comment by Awesome-Logic** [comment] 2020-07-31 12:22
I was using a script to run it, but your method is PERFECT. Thanks for the tips.

BS 1.4 used to work flawlessly out of the box, so this does look like an issue that could be fixed.

**Comment by Dliwk** [comment] 2020-07-31 12:28
I think this issue may be successfully closed.

**Comment by Awesome-Logic** [comment] 2020-07-31 12:37
The issue is still there though, BS 1.5 executable should be executable from file managers.

**Comment by efroemling** [comment] 2020-08-01 22:47
Very interesting. I just tried the technique mentioned [here](https://unix.stackexchange.com/a/324294) and confirmed that 1.5.x binaries seem to be compiled as position-independent and 1.4.x as position-dependent. I don't believe I explicitly changed this at any point so I'll try to track down why this could be different now.

From what I understand, there are negative performance implications to compiling an executable as position-independent, so unless I come across a reason to keep it this way I'll try to do whatever is needed to get it back to position-dependent.

**Comment by efroemling** [comment] 2020-08-01 23:52
Ok, a bit more info I've come across: it seems other people have noticed this same thing: https://leimao.github.io/blog/PIC-PIE/

It sounds like GCC around version 6 or so started doing position-independent-code by default. BS 1.4.x for linux was compiled with GCC 4.8.4 and BA/BS 1.5.24 is currently using GCC 9.3.0, so this might explain why that is different now.

I'm also getting the sense that this is the default now partially because it allows extra security measures such as [ASLR](https://en.wikipedia.org/wiki/Address_space_layout_randomization) and that leaving it enabled may be worth the potential slight performance hit. I generally prefer going with defaults when possible to avoid obscure bugs on 'less traveled paths'.

So even though it might make things annoying in file-managers, I think we should keep this as-is for now. Hopefully the file-managers get updated to treat these as binaries at some point since it sounds like more things will be going this way.
I also still hope to get some of the low-level engine source added to the repo so folks can play with this option if they'd like to test for performance differences/etc...

**Comment by efroemling** [comment] 2020-08-05 19:27
I'll go ahead and close this. Feel free to re-open if you think this is worth further discussion.
To summarize: I think that 'going with defaults' and allowing builds to be position-independent seems reasonable. It might actually be worthwhile to log a bug with the file manager about displaying them as executables; if position-independent is the default now, I would think that they would start showing lots of things incorrectly; not just our stuff.

**Closed by efroemling** 2020-08-05 19:27 UTC
Labels: bug

**Comment by Awesome-Logic** [comment] 2020-08-07 10:08
Turns out, it's a long running issue between Nautilus and file/libmagic project. file/libmagic cannot distinguish between shared objects and executables in a reliable way.

The easiest way is to create a 'run_shared_lib.sh'

```
#!/bin/bash
exec $1
```

Then associate shared-library files with this script.
