### ISSUE TITLE
Freeze every 10-30 sec on old device

### ISSUE THREAD

**Issue by EraOSBeta** [efroemling/ballistica#418] opened 2022-06-04 06:29 UTC
So I decided to test 1.7.1 on an old device, and then I saw that every 10 to 30 seconds, the game freezes for about 5 to 10 seconds, all of the sounds and music keep playing if they were triggered before the freeze, but the game's calculations stop entirety until the game unfreezes. now, you might say: "your playing on an old crappy device of course that's gonna happen", but the issue is that none of the past versions had this happen on the same device, this bug happens both while playing and while in the title screen, both when your signed in to V1 or V2 accounts. I know my device is old, but the fact that it didn't happen before makes it concerning to me, I also just played on 1.6 again to make sure my device wasn't broken, but it worked fine on 1.6.X

Steps to reproduce:
1. Have an old/crappy device
2. Launch BombSquad 1.7.1
3. Bug!

Expected behavior:
Absolutely nothing

Machine:
Android 5.1, Lenovo TB3-710I
BombSquad 1.7.1 (https://files.ballistica.net/bombsquad/builds/BombSquad_Android_Generic_1.7.1.apk)

**Comment by efroemling** [comment] 2022-06-04 17:04
This is definitely worth tracking down. (And part of the reason 1.7 hasn't been pushed to Google Play yet; so we can track down stuff like this first).
Thanks for the report.
I've got some Android 5.x devices so I'll try to give it a whirl there when I have a chance.
Do you by chance have access to a device with [adb](https://developer.android.com/studio/command-line/adb) installed? If so, could you check out the android log and see if there's any scary log messages from bombsquad?
Also, could you try running the network diagnostics in Settings->Advanced->Network Testing and copy/paste the results here if you see anything red?

**Comment by EraOSBeta** [comment] 2022-06-04 18:35
I can't run adb right now since I'm on a trip, but I can do that tomorrow. Network testing shows that I can't contact V1 master-server src1, all other stuff are fully operational:
Running network diagnostics...
ua: BombSquad 1.7.1 TstB (20592) (android 5.1; Lenovo TB3-710I; en_US)
time: 2022-06-04 18:32:58.865091+00:00.

Contacting V1 master-server src0 (https://legacy.ballistica.net)...
Succeeded in 2.45s.

Contacting V1 master-server src1 (https://acrobattleserver.appspot.com)...
Traceback (most recent call last):
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/ba_data/python/bastd/ui/settings/nettesting.py", line 147, in _print_test_results
    call()
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/ba_data/python/bastd/ui/settings/nettesting.py", line 177, in <lambda>
    _print_test_results(lambda: _test_fetch(baseaddr))
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/ba_data/python/bastd/ui/settings/nettesting.py", line 276, in _test_fetch
    response = urllib.request.urlopen(urllib.request.Request(
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Failed in 2.71s.

V1-test-log: only src0 succeeded in 6.491; using src0

V1 src0 result: {'t': '1654367269.3517008'}

V1 src1 result: Traceback (most recent call last):
  File "<string>", line 80, in run
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/data/data/net.froemling.bombsquad/files/ballistica_files/pylib/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

Using V1 address: https://legacy.ballistica.net

Running V1 transaction...
Succeeded in 2.62s.

Contacting V2 master-server (https://ballistica.net)...
Succeeded in 3.35s.

Checking nearest V2 zone ping (me-south-1: 101ms)...
Succeeded in 0.00s.

Diagnostics complete. Some diagnostics failed.

**Comment by efroemling** [comment] 2022-06-04 19:05
> Network testing shows that I can't contact V1 master-server src1, all other stuff are fully operational:

Ok that actually looks pretty normal. src1 is the server's appspot.com address, which is an address provided by Google for App-Engine apps (which the master-server is). A number of places seem to block appspot.com since I'm sure there's some bad actors using those addresses. That's pretty much why there's the alternate address. I should probably have that diagnostic not complain as long as one of the two works.

Curious to hear if adb shows up anything. If not I can try adding some checkboxes to turn off some of the new 1.7 functionality to see if we can pinpoint where that's coming from.

**Comment by NishchayKQ** [comment] 2022-07-05 04:25
Hey I am facing similar issue with the latest build (as of now) although the lag is for 1-2 seconds on a regular interval/navigating through start up menu (like clicking play,account,settings)
My device is Samsung Tab A (SMT595) 

Do note staying on menu screen idle causes this 1.5 sec screen freeze every 30seconds (i used stop watch)

I have access to add but do not know how to do the thing u mentioned above (I could search on web for it,if this info is needed)

**Comment by efroemling** [comment] 2022-07-06 00:14
Ok I've been able to reproduce this problem on my test Android devices. It seems the game is hitching for about half a second pretty frequently while it attempts to obtain the Python [GIL](https://wiki.python.org/moin/GlobalInterpreterLock). I'm looking into what could be causing this to happen now when it wasn't before. There is some new background thread stuff running now which could be at fault or perhaps its some change in Python 3.10.  I'll keep digging.

I've also noticed that the same type of hitch happens when I open Settings->Advanced.  Are you folks seeing that too?

**Comment by NishchayKQ** [comment] 2022-07-06 00:48
Yes each time I click on advanced

**Comment by efroemling** [comment] 2022-07-06 00:57
Ok I'm hopeful that I've figured it out.
I found that the freeze in the Advanced window goes away if I stop the window from sending out a https request to the v1-master-server (which it does to ask about language statuses). But interestingly it *also* goes away if I change that request from https to plain old insecure http. So it seems like something related to SSL is holding on to the GIL which brings the game to a screeching halt whenever a web request happens.

Poking around, I just came across [this](https://github.com/python/cpython/issues/88311) which makes it sound like Python 3.10.4 has a bug causing https requests to not properly release the GIL. I'm guessing that might be exactly what we're seeing. It sounds like it should be fixed in 3.10.5 so I'll rebuild our Python libraries with that update and with any luck we'll be good to go again.  Fingers crossed. 🤞

(apologies if any/all of this sounded like gibberish; just thinking out loud)

**Comment by NishchayKQ** [comment] 2022-07-06 01:07
Yay ! Yep I dont have any technical knowledge but I kinda understand , let's hope for the best!

**Comment by efroemling** [comment] 2022-07-06 01:41
Well rats; updating to 3.10.5 didn't fix it so I guess it's not that particular GIL issue. I at least know its something related to SSL and the GIL though so I can hopefully get to the bottom of it before too long.

**Comment by efroemling** [comment] 2022-07-06 23:59
Ok, after a long day of digging I'm happy to say this should be fixed. Can you grab the latest Android [build](https://ballistica.net/builds) and let me know if you are still seeing any hitching? It should be behaving as of 1.7.3 build 20634.

Basically, I turned on secure networking a while back as part of the 1.7 update, and it turns out there's a particular call related to that which is taking strangely long on Android (perhaps mostly on older devices?..).  This call basically prevents any other Python code from running while it runs, which is why the main game thread hitches at those times.

I've fixed my custom Android builds of Python to allow other code to run during that call, and I also submitted a [bug report](https://github.com/python/cpython/issues/94637) to Python so maybe they'll do the same fix on their end in case it shows up on any other platforms.

**Comment by NishchayKQ** [comment] 2022-07-07 02:10
Yes Eric it works on my device too(no freezing in menu screen/options/gameplay). Awesome !

**Comment by efroemling** [comment] 2022-07-09 16:45
Good news: this fix has just made into Python: https://github.com/python/cpython/commit/a61870e19602f54a0579dd83edf334ba00ad92f6

So a big thanks @EraOSBeta and @NishchayKQ for reporting this and helping test this. You've indirectly improved Python itself ;)

I'll go ahead and close this now. Please holler if you run into any similar hitching anywhere else.

**Closed by efroemling** 2022-07-09 16:45 UTC
Labels: bug
