### ISSUE TITLE
Spaz Bigger than it should be

### ISSUE THREAD

**Issue by PythonCode-blip** [efroemling/ballistica#151] opened 2020-08-06 02:57 UTC
This was a bug that was on earlier versions of the game and somehow it came back, it also makes the spaz bigger just by jumping repeatedly (doesn't work in Happy Thoughts) and giving you an advantage in battle.
![Screenshot_2020-08-05-19-54-40](https://user-images.githubusercontent.com/66983599/89485518-d0977400-d755-11ea-98ca-456b790bfb0c.png)

**Comment by TheMikirog** [comment] 2020-09-24 08:30
First of all, that's not a bug - it's a quirk of the engine and how jumping works. You extend legs to jump and spamming the button results in that.

Second, this doesn't give you an advantage in battle at all. Yes, hitting the head is difficult, but you move ridiculously slowly and for a game about speed, gimping yourself like that is not worth it.

Why are we talking about this?

**Comment by YairMejiaValtierra** [comment] 2020-09-24 18:35
> First of all, that's not a bug - it's a quirk of the engine and how jumping works. You extend legs to jump and spamming the button results in that.
> 
> Second, this doesn't give you an advantage in battle at all. Yes, hitting the head is difficult, but you move ridiculously slowly and for a game about speed, gimping yourself like that is not worth it.
> 
> Why are we talking about this?

but bro u dont understand in 1.5 servers asia that does give an advantage because when u jump and the spaz at 60° angle to left or right and the swipe or joystifk is at the same velocity of where u go the jump is bigger than bombjump and u can literally just punch a spaz head off and giving u an insane amounted spead but this never happrn in 1.4 it was a weak punch before and it kinda gave u an adbantage it will still give u -100% dmg but in 1.5 it always give u over -180% dmg so this is too op and it ruins my gameplay for players spaz users it is annoying it will make players mad anf quit

**Comment by YairMejiaValtierra** [comment] 2020-09-24 18:39
Also why im saying Asia? is because that is the majority of where it happens same with SudAmerica servers

**Comment by Dliwk** [comment] 2021-01-13 20:39
I think TheMikrog is right (why the funny game feature is a bug? I would call it bug if the spaz then flew up, the sky turned green and the map fell to pieces), so I'll close this. 

Reopen if you don't agree and want to discuss.

**Closed by Dliwk** 2021-01-13 20:39 UTC
