### ISSUE TITLE
Telugu text not rendering

### ISSUE THREAD

**Issue by Blaze-Corderz** [efroemling/ballistica#720] opened 2024-08-03 09:06 UTC
### Description
Telugu text is not being renderd

### Steps to reproduce
1. Launch BombSquad
2. In any place where you can input text, type telugu text
4. Bug!

### Expected behavior
Describe what you think should happen if it's not obvious.

### Machine
**Platform**: Windows 11
**BombSquad version**: [1.7.32](https://github.com/efroemling/ballistica/tree/v1.7.32) \
**Commit**: https://github.com/efroemling/ballistica/tree/978f32f9f098bd0ff1dc64b496ec31cf493ded09

You may specify BombSquad version you're running or refer to the latest commit.

### Screenshots
Put some screenshots here if needed.

### Extra
You may put some extra information here. For example, describe your assumptions about the cause of the bug.

**Comment by EraOSBeta** [comment] 2024-08-04 15:45
This happens with a lot of languages, it is planned to be fixed before 2.0 (the Steam release)

**Comment by Dliwk** [comment] 2024-08-04 19:05
Hi there; yes, requested many times, I'll close this as duplicate of #45 #367 #523. (See a bit more explanations there).

**Closed by Dliwk** 2024-08-04 19:05 UTC
Labels: bug
