### ISSUE TITLE
Incorrect shield rendering

### ISSUE THREAD

**Issue by Dliwk** [efroemling/ballistica#450] opened 2022-06-28 16:11 UTC
### Description
Shield can get blurred just like background when it shouldn't.

### Screenshots
![изображение](https://user-images.githubusercontent.com/47295209/176228080-0f3b7828-258e-4965-8b31-8a2ea7b0f0ad.png)
![изображение](https://user-images.githubusercontent.com/47295209/176227853-5cdbcf9a-503c-41d0-8ccc-f69b0e3d400a.png)

**Comment by efroemling** [comment] 2022-06-30 16:40
Though not ideal, this is the expected behavior. The depth-of-field effect works by taking the final rendered scene and a blurred version of it and blending them based on the depth buffer. Depth values close to the camera's focus point use the sharp version and values farther away use more of the blurred version.

The shield effect draws as transparent and generally transparent things don't write to the depth buffer (since that would prevent things behind them from drawing even though you would expect to see them through a transparent object). Because of this, the depth value for where the shield draws is really just the depth value for what's behind it, and it gets blurred as such. So the part of the shield over the wood foreground is *not* blurred since that depth value is close to the camera focus and the part over the background *is* blurred since that depth value is far away.

One thing we could do is have the shield draw itself in the 'overlay' pass which happens *after* the sharp and blurred backgrounds have been combined, but then it would always draw perfectly sharp which might not be ideal either. So we'd need to make the shader smart enough to blur itself based on whether it is in focus or not so it maches the depth-of-field near it. Things like this would add some expense though which is part of the reason I didn't go that route originally and left it in its imperfect state. We could certainly improve it now though since low-end hardware is much faster than it was when I was originally writing this.

Hope that all makes sense?..

**Comment by efroemling** [comment] 2022-07-20 22:38
(will close this now, as it is working as designed)

**Closed by efroemling** 2022-07-20 22:38 UTC
Labels: bug
