### ISSUE TITLE
No Preparing your Environment for Coding on Android 

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#109] opened 2020-07-14 04:52 UTC
I think the title is self explanatory, we have no Preparing your Environment for Android platform in the Getting Started page of Ballistica Wiki.

**Comment by efroemling** [comment] 2020-07-14 08:34
Duplicate of #73

**Comment by Benefit-Zebra** [comment] 2020-07-14 16:20
@efroemling I meant that, you have given all the things like How to Set Up Environment, IDEs, Debugging, Format code, for Windows, Mac, and Linux. You have not mentioned anything that of such for Android.

**Comment by efroemling** [comment] 2020-07-14 20:03
Reopening this as I suppose discussion of Android as a development environment is different from discussion of Android as a build target (as in #73).

I'm currently not familiar with the process of doing editing/etc. ON an Android device. I imagine such things are possible (via [termux](https://termux.com), etc.) but I haven't attempted it. Does anyone here do such things who could talk about it?

If someone would like to do so and modify the wiki pages to include working on Android I'd be happy to help fix any issues that come up. The ballistica toolset is all generic unix/python stuff so hopefully a decent amount of it would work in something like Termux.

**Comment by efroemling** [comment] 2020-07-14 20:12
On a side note I wanted to mention what I think would be a fun project: setting up a server which has the ballistica build tools and is serving an online editor UI like [atom](https://atom.io) or [theia](https://www.theia-ide.org). This could be plugged into the ballistica formatting/checking tools such as [mypy](https://atom.io/packages/linter-mypy) to make it really easy to write correct code and could have a download button or whatnot to fetch the script once done.
I think something like that could make modding on systems like Android pretty accessible with just a web browser and no need to set up a complex build environment. I hope to try something like this one day, though I have lots of other things on my to-do list right now.

**Comment by Benefit-Zebra** [comment] 2020-07-15 05:33
@efroemling I have created a Wiki page in which I have given the Environment which I use on my Device. Can you Please go through it.

https://github.com/efroemling/ballistica/wiki/Coding-Environment-for-Android

**Comment by efroemling** [comment] 2020-07-15 07:32
> @efroemling I have created a [Wiki page](https://github.com/efroemling/ballistica/wiki/Coding-Environment-for-Android) in which I have given the Environment which I use on my Device.
> Can you Please go through it.

Thanks for writing that! A few notes/questions:
- It might be nice to start with a bit of an overview about what this allows one to do. It might be good to mention that this is different from the 'standard' ballistica pipeline but allows syntax-checking and formatting directly on Android (just so people don't get confused and start asking how to do 'make prefab' and all that usual stuff here)
- I'd maybe also include a quick explanation of the part where you download _ba.py so users know why they are doing that. (basically that 'real' _ba exists only within the running game and this allows offline tools to look up _ba stuff)
- The 'Data theft' mention in ES File Explorer sounds a bit scary. Could you add a link about that so people know the risks? I did a quick search and came up with [this](https://trak.in/tags/business/2019/01/16/10-crore-android-users-at-risk-of-data-theft-es-file-explorer-has-a-hidden-web-server/) as an example.

If you don't mind making those few adjustments then I'd love to add a link to that page from the standard 'Getting Started' page. Thanks again!

**Comment by Benefit-Zebra** [comment] 2020-07-15 14:04
I have made the adjustments and updated the [page](https://github.com/efroemling/ballistica/wiki/Coding-Environment-for-Android). Check and tell me if anything else is missing.

**Comment by efroemling** [comment] 2020-07-17 09:38
Cool; thanks!
I added a mention of 'Other Environments' to the [Getting Started](https://github.com/efroemling/ballistica/wiki/Getting-Started) page with a link to your page 👍.

**Comment by efroemling** [comment] 2020-07-23 00:51
I'll go ahead and close this for now; feel free to re-open if there's more to discuss. And please feel free to keep that wiki page updated with any future changes to your editing environment, and thanks again for writing it. 👍

**Closed by efroemling** 2020-07-23 00:51 UTC
Labels: discussion, help wanted

**Comment by Benefit-Zebra** [comment] 2020-07-25 11:07
@efroemling I have got a way to make **prefab on Android _for other platforms_** since we don't have prefab pipeline for Android. By using this, Android Users can do all the things Windows/Linux users could do from making a prefab to testing and formatting. I want to ask for your permission to edit the Getting Started page though I know I am free to edit it. Building the page would take few days.

**Comment by Benefit-Zebra** [comment] 2020-07-28 09:04
@efroemling I have got a way to make **prefab on Android _for other platforms_** since we don't have prefab pipeline for Android. By using this, Android Users can do all the things Windows/Linux users could do from making a prefab to formatting. I want to ask for your permission to edit the Getting Started page though I know I am free to edit it. Building the page would take few days.

**Comment by Benefit-Zebra** [comment] 2020-07-28 16:29
@efroemling I have got a way to make **prefab on Android _for other platforms_** since we don't have prefab pipeline for Android. By using this, Android Users can do all the things Windows/Linux users could do from making a prefab to formatting. I want to ask for your permission to edit the Getting Started page though I know I am free to edit it.

**Comment by efroemling** [comment] 2020-08-02 04:07
@Benefit-Zebra So you have a way to use all the existing makefiles and scripts and whatnot on Android? If that is the case and it is possible to add a section similar to the Mac, Linux, or Windows section then I would say go for it 👍. But if the Android pipeline is significantly different than the others then I think it is best to keep it in its own page (like the current 'Coding Environment for Android')

**Comment by Benefit-Zebra** [comment] 2020-08-02 05:10
> But if the Android pipeline is significantly different than the others then I think it is best to keep it in its own page (like the current 'Coding Environment for Android')

Since we don't have pipeline for Android, we can't make prefab **for Android** but **we can make prefab for platforms such as Mac, Linux, and Windows _on Android._ **

**Comment by efroemling** [comment] 2020-08-02 05:15
> > But if the Android pipeline is significantly different than the others then I think it is best to keep it in its own page (like the current 'Coding Environment for Android')
> 
> Since we don't have pipeline for Android, we can't make prefab **for Android** but **we can make prefab for platforms such as Mac, Linux, and Windows _on Android._**

If it is possible to use most of the standard pipeline tools (`make format`, `make check`, etc.) then I think adding an Android section to the docs would be worthwhile. Someone might take the time to implement a `make prefab` for Android later. (essentially taking an existing APK and re-signing it with a new set of scripts)

**Comment by Benefit-Zebra** [comment] 2020-08-02 10:41
@efroemling I have updated the [Getting Started](https://github.com/efroemling/ballistica/wiki/Getting-Started). 

Please see if anything needs to be updated or any information is missing or anything I have written is hard to understand.
